Repository kevinpapst/TablerBundle, pull requests merged in 2021-12, with the labels that each got.

#25 [Feature] Embed card - Allow footer to be collapsed
  templates/embeds/card.html.twig
Labels: Status: Reviewed, Feature

#18 Feature - Icons on child items menu
  templates/includes/menu.html.twig
Labels: Status: Reviewed, Feature

#4 BugFix - login page render when default values from tabler.yaml
  src/DependencyInjection/Configuration.php
  templates/security.html.twig
  tests/DependencyInjection/ConfigurationTest.php
Labels: Bug, Status: Reviewed

#6 Add `tabindex` on login form inputs
  templates/security.html.twig
Labels: Status: Needs Review, Feature

#31 [Templating] Added block page_header to default layout
  templates/layout.html.twig
Labels: Status: Needs Review, Feature
