Repository kevinpapst/TablerBundle, pull requests merged in 2022-09, with the labels that each got.

#103 Create accordion.html.twig
  docs/components-accordion.md
  templates/components/accordion.html.twig
Labels: Feature, Status: Needs Work

#107 Update components-accordion.md
  docs/components-accordion.md
Labels: Documentation, Status: Needs Review

#111 handle null URL in navigation/menu models
  templates/includes/menu.html.twig
  templates/includes/navbar_user.html.twig
Labels: Bug, Status: Reviewed

#112 Add more modal class blocks
  templates/embeds/modal.html.twig
Labels: Status: Needs Review, Feature

#113 BugFix themes link
  docs/form_theme.md
Labels: Documentation, Status: Needs Review

#115 Update theme override doc
  docs/theme.scss
Labels: Documentation, Status: Needs Review
