Repository kevinpapst/TablerBundle, pull requests merged in 2022-01, with the labels that each got.

#47 [Feature] Add TWIG submit_button() macro
  templates/components/button.html.twig
  templates/components/buttons.html.twig
Labels: Status: Reviewed, Feature

#50 [Feature] Add modal `start` blocks
  templates/embeds/modal.html.twig
Labels: Status: Needs Review, Feature

#48 [BugFix] Reorder blocks to match breadcrumb from Tabler.io doc
  templates/layout.html.twig
Labels: Bug, Status: Needs Review

#32 [Feature] Button macro - Simplified it
  docs/components-buttons.md
  docs/index.md
  docs/layout.md
  docs/migration_guide.md
  templates/components/button.html.twig
Labels: Status: Needs Review, Feature

#46 [Feature] Add error layout + layout fullpage
  config/packages/tabler.yaml
  docs/error_pages.md
  docs/index.md
  docs/layout.md
  templates/error.html.twig
  templates/fullpage.html.twig
  translations/TablerBundle.de.xliff
  translations/TablerBundle.en.xliff
  translations/TablerBundle.fr.xliff
Labels: Status: Reviewed, Feature

#52 Fixes (best PR name in the world!)
  docs/index.md
  docs/layout.md
  docs/twig-context.md
  templates/embeds/card.html.twig
  templates/error.html.twig
Labels: Status: Reviewed, Feature

#56 [BugFix] Update flash to Tabler template
  templates/components/flash.html.twig
Labels: Bug, Status: Needs Review

#59 BugFix tooltip when title displayed in raw HTML
  templates/components/button.html.twig
Labels: Bug, Status: Needs Review

#55 Add theme override example/doc
  docs/index.md
  docs/theme/override_theme.md
  docs/theme/theme.scss
Labels: Documentation, Status: Needs Work

#61 Add timeline Tabler component
  docs/components-timeline.md
  docs/index.md
  templates/components/timeline.html.twig
Labels: Status: Reviewed, Feature
