Repository kevinpapst/TablerBundle, pull requests merged in 2023-01, with the labels that each got.

#129 [Card] Add Card component with nav
  docs/embeds-card-nav.md
  templates/embeds/card_nav.html.twig
  templates/embeds/card_nav_header.html.twig
Labels: Feature, Status: Needs Work

#132 Update README.md
  README.md
Labels: Documentation

#133 [Card] Refactoring V1
  templates/embeds/card.html.twig
Labels: Status: Reviewed, Feature

#139 added release drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yaml
Labels: Feature
